import Dashboard from "@/components/dashboard/dashboard";
import { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Dashboard />
    </div>
  );
};

export default page;
